#pragma once

// All minion types/names
enum class MinionType : unsigned char {
  NONE,
  // Tier 1
  AlleyCat,
  DireWolfAlpha,
  Mecharoo,
  MicroMachine,
  MurlocTidecaller,
  MurlocTidehunter,
  RighteousProtector,
  RockpoolHunter,
  SelflessHero,
  Voidwalker,
  VulgarHomunculus,
  WrathWeaver,
  // Tier 1 tokens
  TabbyCat,
  JoEBot,
  MurlocScout,
  AmalgamToken,
  Plant,
  // Tier 2
  AnnoyOTron,
  HarvestGolem,
  KaboomBot,
  KindlyGrandmother,
  MetaltoothLeaper,
  MountedRaptor,
  MurlocWarleader,
  NathrezimOverseer,
  NightmareAmalgam,
  OldMurkEye,
  PogoHopper,
  RatPack,
  ScavengingHyena,
  ShieldedMinibot,
  SpawnOfNZoth,
  Zoobot,
  // Tier 2 tokens
  DamagedGolem,
  BigBadWolf,
  Rat,
  // Tier 3
  CobaltGuardian,
  ColdlightSeer,
  CrowdFavorite,
  Crystalweaver,
  Houndmaster,
  ImpGangBoss,
  InfestedWolf,
  Khadgar,
  PackLeader,
  PhalanxCommander,
  PilotedShredder,
  PsychOTron,
  ReplicatingMenace,
  ScrewjankClunker,
  ShifterZerus,
  SoulJuggler,
  TortollanShellraiser,
  // Tier 3 tokens
  Microbot,
  Spider,
  Imp,
  // Tier 4
  AnnoyOModule,
  BolvarFireblood,
  CaveHydra,
  DefenderOfArgus,
  FesterootHulk,
  IronSensei,
  Junkbot,
  MenagerieMagician,
  PilotedSkyGolem,
  SecurityRover,
  Siegebreaker,
  TheBeast,
  Toxfin,
  VirmenSensei,
  // Tier 4 tokens
  GuardBot,
  FinkleEinhorn,
  // Tier 5
  AnnihilanBattlemaster,
  BaronRivendare,
  BrannBronzebeard,
  GoldrinnTheGreatWolf,
  IronhideDirehorn,
  LightfangEnforcer,
  MalGanis,
  MechanoEgg,
  PrimalfinLookout,
  SatedThreshadon,
  SavannahHighmane,
  StrongshellScavenger,
  TheBoogeymonster,
  // Tier 5 tokens
  IronhideRunt,
  Robosaur,
  Hyena,
  // Tier 6
  FoeReaper4000,
  GentleMegasaur,
  Ghastcoiler,
  KangorsApprentice,
  Maexxna,
  MamaBear,
  OldMamaBear, // pre nerf
  SneedsOldShredder,
  Voidlord,
  ZappSlywick,
  //
  COUNT
};
